\c sneakers_db;

INSERT INTO sneakers
    (brand, model, price, category, color, is_favorite)
VALUES
    ('Nike', 'Air Max 90', 120, 'Running', 'Red', false),
    ('Adidas', 'UltraBoost', 180, 'Running', 'Black', true),
    ('Puma', 'Suede Classic', 70, 'Casual', 'Blue', false),
    ('Reebok', 'Club C 85', 75, 'Casual', 'White', true),
    ('Under Armour', 'Curry 8', 160, 'Basketball', 'Yellow', false),
    ('New Balance', '990v5', 175, 'Running', 'Grey', true),
    ('Asics', 'Gel-Kayano 27', 160, 'Running', 'Green', false),
    ('Converse', 'Chuck Taylor All Star', 55, 'Casual', 'Black', true),
    ('Vans', 'Old Skool', 60, 'Casual', 'Red', false),
    ('Jordan', 'Air Jordan 1', 150, 'Basketball', 'Blue', true),
    ('Fila', 'Disruptor 2', 65, 'Casual', 'White', false),
    ('Skechers', 'D-Lites', 55, 'Casual', 'Black', true),
    ('Saucony', 'Jazz Original', 70, 'Running', 'Grey', false),
    ('Mizuno', 'Wave Rider 24', 130, 'Running', 'Blue', true),
    ('Brooks', 'Ghost 13', 130, 'Running', 'Purple', false),
    ('Hoka One One', 'Clifton 7', 130, 'Running', 'Green', true),
    ('Salomon', 'Speedcross 5', 130, 'Trail Running', 'Red', false),
    ('Merrell', 'Moab 2', 100, 'Hiking', 'Brown', true),
    ('La Sportiva', 'Bushido II', 130, 'Trail Running', 'Yellow', false),
    ('Altra', 'Lone Peak 5', 120, 'Trail Running', 'Grey', true),
    ('On Running', 'Cloud X', 140, 'Running', 'Black', false),
    ('Inov-8', 'Terraultra G 270', 160, 'Trail Running', 'Green', true),
    ('Topo Athletic', 'Ultrafly 3', 130, 'Running', 'Blue', false),
    ('361 Degrees', 'Meraki 4', 120, 'Running', 'Yellow', true),
    ('Newton', 'Gravity 9', 175, 'Running', 'Red', false),
    ('K-Swiss', 'Hypercourt Express', 100, 'Tennis', 'White', true),
    ('Diadora', 'Mythos Blushield', 130, 'Running', 'Blue', false),
    ('Karhu', 'Ikoni Ortix', 130, 'Running', 'Purple', true),
    ('Vivobarefoot', 'Primus Lite III', 140, 'Barefoot', 'Black', false),
    ('Xero Shoes', 'HFS', 110, 'Barefoot', 'Grey', true),
    ('Lems', 'Primal 2', 105, 'Barefoot', 'Brown', false),
    ('North Face', 'Ultra 111 WP', 120, 'Trail Running', 'Green', true),
    ('Arcteryx', 'Norvan SL', 150, 'Trail Running', 'Black', false),
    ('Scarpa', 'Spin Ultra', 150, 'Trail Running', 'Red', true),
    ('Dynafit', 'Feline SL', 130, 'Trail Running', 'Blue', false),
    ('Columbia', 'Montrail Caldorado III', 120, 'Trail Running', 'Yellow', true),
    ('Icebug', 'Acceleritas8', 130, 'Trail Running', 'Green', false),
    ('Inov-8', 'Roclite G 275', 140, 'Trail Running', 'Grey', true),
    ('Topo Athletic', 'Mountain Racer', 140, 'Trail Running', 'Blue', false),
    ('Hoka One One', 'Speedgoat 4', 145, 'Trail Running', 'Red', true),
    ('Altra', 'Timp 3', 140, 'Trail Running', 'Black', false),
    ('La Sportiva', 'Akasha II', 160, 'Trail Running', 'Yellow', true),
    ('Merrell', 'Antora 2', 110, 'Trail Running', 'Green', false),
    ('Nike', 'Pegasus Trail 2', 130, 'Trail Running', 'Blue', true),
    ('Salomon', 'XA Pro 3D V8', 130, 'Trail Running', 'Red', false),
    ('New Balance', 'Hierro v5', 135, 'Trail Running', 'Black', true),
    ('Brooks', 'Cascadia 15', 130, 'Trail Running', 'Yellow', false),
    ('Saucony', 'Peregrine 11', 120, 'Trail Running', 'Green', true);